### ISSUE TITLE
Error on expressValidator when running Server

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer-server#187]
When the server is run, an error is displayed :

```
lionel@lionel-sugarizer:~/src/olpc/sugarizer-server$ node sugarizer.js
FATAL ERROR, uncaught exception 'expressValidator is not a function'
TypeError: expressValidator is not a function
    at module.exports (/home/lionel/src/olpc/sugarizer-server/config/main.js:46:10)
    at /home/lionel/src/olpc/sugarizer-server/sugarizer.js:31:26
    at /home/lionel/src/olpc/sugarizer-server/config/wait4db.js:20:6
    at result (/home/lionel/src/olpc/sugarizer-server/node_modules/mongodb/lib/utils.js:410:17)
    at executeCallback (/home/lionel/src/olpc/sugarizer-server/node_modules/mongodb/lib/utils.js:402:9)
    at err (/home/lionel/src/olpc/sugarizer-server/node_modules/mongodb/lib/operations/mongo_client_ops.js:286:5)
    at connectCallback (/home/lionel/src/olpc/sugarizer-server/node_modules/mongodb/lib/operations/mongo_client_ops.js:265:5)
    at server.connect (/home/lionel/src/olpc/sugarizer-server/node_modules/mongodb/lib/operations/mongo_client_ops.js:379:5)
    at Server.connectHandler (/home/lionel/src/olpc/sugarizer-server/node_modules/mongodb/lib/topologies/server.js:298:9)
    at Object.onceWrapper (events.js:286:20)
lionel@lionel-sugarizer:~/src/olpc/sugarizer-server$ 
```

**Comment by llaske** [comment]
The current work around is to change `package.json` [line 16](https://github.com/llaske/sugarizer-server/blob/master/package.json#L16) from

            "express-validator": ">=5.3.1",

To

             "express-validator": "5.3.1",
