### ISSUE TITLE
Unit tests are broken for activities

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer-server#273]
When launching unit test, there is an error message.

```
> sugarizer-server@1.3.0 test
> mocha api/test/ --timeout 20000



  Activities
   _____                        _              
  / ____|                      (_)             
 | (___  _   _  __ _  __ _ _ __ _ _______ _ __ 
  \___ \| | | |/ _` |/ _` | '__| |_  / _ \ '__|
  ____) | |_| | (_| | (_| | |  | |/ /  __/ |   
 |_____/ \__,_|\__, |\__,_|_|  |_/___\___|_|   
                __/ |                          
               |___/                           
Server for Sugarizer application v1.3.0
node v15.0.1
Settings file './env/test.ini'
Presence is listening on port 8039...
API is listening on port 8080...
    /GET activities
      ✓ it should return all the activities
      ✓ it should return all fields
FATAL ERROR, uncaught exception 'expected 40 to deeply equal 3'
AssertionError: expected 40 to deeply equal 3
    at /home/lionel/src/olpc/sugarizer-server/api/test/activities.js:92:32
    at Test.Request.callback (/home/lionel/src/olpc/sugarizer-server/node_modules/chai-http/node_modules/superagent/lib/node/index.js:716:12)
    at /home/lionel/src/olpc/sugarizer-server/node_modules/chai-http/node_modules/superagent/lib/node/index.js:916:18
    at IncomingMessage.<anonymous> (/home/lionel/src/olpc/sugarizer-server/node_modules/chai-http/node_modules/superagent/lib/node/parsers/json.js:19:7)
    at IncomingMessage.emit (node:events:339:22)
    at endReadableNT (node:internal/streams/readable:1289:12)
    at processTicksAndRejections (node:internal/process/task_queues:80:21)
npm ERR! code 255
npm ERR! path /home/lionel/src/olpc/sugarizer-server
npm ERR! command failed
npm ERR! command sh -c mocha api/test/ --timeout 20000

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lionel/.npm/_logs/2020-11-07T15_22_13_939Z-debug.log
```

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/commit/736d5d470034932c15bb8c46847783e18192c58f
Unit testing expect to have a limited number (3) of favorite activities. Was increased to 40 by https://github.com/llaske/sugarizer-server/commit/8332e0848edb7afce7bad9286a195cdae7ce60c6.
